# Generated by Django 5.2.6 on 2025-09-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('sl', 'self'), ('bsn', 'bsn'), ('std', 'std')], default='self', max_length=20),
        ),
    ]
